apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backingimages.longhorn.io
spec:
 conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1beta2","v1beta1"]
      clientConfig:
        service:
          namespace: longhorn-system
          name: longhorn-conversion-webhook
          path: /v1/webhook/conversion
          port: 9501
