name: Create CRD and Manifest Update PR in Longhorn Repo

on:
  pull_request_target:
    types: [closed]
    branches:
      - master
      - "v*"

jobs:
  create-pull-request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Packages
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Log triggering PR information
      shell: bash
      run: |
        echo "Triggered by PR: #${{ github.event.pull_request.number }}"
        echo "PR Title: ${{ github.event.pull_request.title }}"
        echo "PR URL: ${{ github.event.pull_request.html_url }}"
        echo "PR was merged into branch: ${{ github.event.pull_request.base.ref }}"
    - uses: actions/checkout@v4
      with:
        repository: longhorn/longhorn
        ref: ${{ github.event.pull_request.base.ref }}

    - name: Update crds.yaml and manifests
      shell: bash
      run: |
        curl -fL "https://github.com/longhorn/longhorn-manager/raw/${{ github.event.pull_request.base.ref }}/k8s/crds.yaml" -o chart/templates/crds.yaml
        bash scripts/generate-longhorn-yaml.sh
        bash scripts/helm-docs.sh

    - name: Get Head Commit Name
      id: get_head_commit_name
      run: echo "::set-output name=commit_name::$(git log -1 --pretty=format:'%an')"

    - name: Get Head Commit Email
      id: get_head_commit_email
      run: echo "::set-output name=commit_email::$(git log -1 --pretty=format:'%ae')"

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        branch: "update-crds-and-manifests-longhorn-manager-${{ github.event.pull_request.number }}"
        delete-branch: true
        sign-commits: true
        signoff: true
        author: ${{ steps.get_head_commit_name.outputs.commit_name }} <${{ steps.get_head_commit_email.outputs.commit_email }}>
        committer: ${{ steps.get_head_commit_name.outputs.commit_name }} <${{ steps.get_head_commit_email.outputs.commit_email }}>
        commit-message: "chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#${{ github.event.pull_request.number}})"
        title: "chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#${{ github.event.pull_request.number}})"
        body: |
          This PR updates the crds.yaml and manifests.
          It was triggered by longhorn/longhorn-manager#${{ github.event.pull_request.number}}.